name: Build and Publish LaTeX PDF

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for committing back

      - name: Set up TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base

      - name: Compile LaTeX to PDF
        run: |
          mkdir -p output
          pdflatex -output-directory=output main.tex

      - name: Commit PDF to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/main.pdf
          git commit -m "Auto-compiled PDF from main.tex [skip ci]" || echo "No changes to commit"
          git push
